# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ef12e44a-f0a3-441c-97ab-d286a9cae562'

- task: DotNetCoreInstaller@0
  displayName: 'Install .net core 3.0 (preview)'
  inputs:
    version: '3.0.100-preview9-014004'

- task: DotNetCoreCLI@0
  displayName: Build
  inputs:
    command: build
    projects: '$(Parameters.projects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@0
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- script: dotnet test SampleWebApp --logger trx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@0
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: dotnet test SampleWebApp --logger trx --collect "Code coverage"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@0
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'nugetCore'

- script: dotnet pack /p:PackageVersion=1.0.0  # define version variable elsewhere in your pipeline
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishVstsFeed: 'ef12e44a-f0a3-441c-97ab-d286a9cae562'
    allowPackageConflicts: true
    versioningScheme: byEnvVar
    versionEnvVar: version

- task: 'PublishBuildArtifacts@1'